# Task 1: Array Basics (Numpy)

In [ ]:
import numpy as np

## 1. Create Arrays

In [ ]:
integers_0_to_9 = np.arange(0, 10, 1) # From 0 to 10 with steps of 1
integers_0_to_9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.randint(
    low=1,       # Inclusive lower bound
    high=101,    # Exclusive upper bound
    size=(3, 3)) # 3 x 3 matrix

array([[76, 42, 62],
       [11, 23, 62],
       [24, 49, 70]])

## 2. Reshape Arrays

In [ ]:
integers_0_to_9.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## 3. Array Attributes

In [ ]:
integers_0_to_9.shape

(10,)

In [ ]:
integers_0_to_9.size

10

In [ ]:
integers_0_to_9.dtype

dtype('int64')



---



# Task 2: Data Manipulation (Pandas)

In [ ]:
import pandas as pd

## 1. DataFrame Creation

In [ ]:
df = pd.DataFrame(
    data = [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [3, 1, 4],
        [64, 5, 3]
    ],
    columns = ['A', 'B', 'C']
)
df

A  B  C
0   1  2  3
1   4  5  6
2   7  8  9
3   3  1  4
4  64  5  3

## 2. Basic Operations

In [ ]:
df[:2] # First two rows

A  B  C
0  1  2  3
1  4  5  6

In [ ]:
for column in df.columns:
    print(f"Mean of column {column} is: {df[column].mean()}")

Mean of column A is: 15.8
Mean of column B is: 4.2
Mean of column C is: 5.0


In [ ]:
column_d = df['A'] + df['B']
df.insert(
    loc=df.shape[1], # Last position
    column='D',      # Column name
    value=column_d   # Column values
)
df

A  B  C   D
0   1  2  3   3
1   4  5  6   9
2   7  8  9  15
3   3  1  4   4
4  64  5  3  69

## 3. Filtering and Sorting

In [ ]:
df['A'].where(df['A'] > 50).dropna()

4    64.0
Name: A, dtype: float64

In [ ]:
df.sort_values(by='C', ascending=False)

A  B  C   D
2   7  8  9  15
1   4  5  6   9
3   3  1  4   4
0   1  2  3   3
4  64  5  3  69



---



# Task 3: Numerical Computations (Numpy)

In [ ]:
import numpy as np

## 1. Element-Wise Operations

In [ ]:
arr1 = np.random.randint(low=1, high=101, size=10)
arr2 = np.random.randint(low=1, high=101, size=10)
print(arr1)
print(arr2)

[49 76 28 20 66 24 30 26 47 19]
[72 90 73 12 67 54 44 59 29 89]


In [ ]:
arr1 + arr2

array([121, 166, 101,  32, 133,  78,  74,  85,  76, 108])

In [ ]:
arr1 - arr2

array([-23, -14, -45,   8,  -1, -30, -14, -33,  18, -70])

In [ ]:
arr1 * arr2

array([3528, 6840, 2044,  240, 4422, 1296, 1320, 1534, 1363, 1691])

## 2. Aggregate Functions

In [ ]:
arr1.mean()

38.5

In [ ]:
arr1.sum()

385

In [ ]:
arr1.std()

19.01709757034443

## 3. Matrix Multiplication

In [ ]:
arr1 = np.random.randint(low=1, high=101, size=(2, 3))
arr2 = np.random.randint(low=1, high=101, size=(3, 2))
print(arr1)
print(arr2)

[[22 32 37]
 [10 12 14]]
[[32 82]
 [32 87]
 [75 33]]


In [ ]:
arr1.dot(arr2)

array([[4503, 5809],
       [1754, 2326]])



---



# Task 4:

In [138]:
import numpy as np
import pandas as pd

## 1. Temperature Analysis

In [ ]:
days = np.array(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'])
temperatures = np.array([72, 68, 74, 71, 69, 73, 75])
print(days)
print(temperatures)

['Monday' 'Tuesday' 'Wednesday' 'Thursday' 'Friday' 'Saturday' 'Sunday']
[72 68 74 71 69 73 75]


In [ ]:
mean_temperature = temperatures.mean()
mean_temperature

71.71428571428571

In [ ]:
filter = temperatures > mean_temperature
print(f"Days with temperatures above the mean: {days[filter]}")

Days with temperatures above the mean: ['Monday' 'Wednesday' 'Saturday' 'Sunday']


## 2. DataFrame Operations

In [ ]:
df = pd.DataFrame(
    data = {
        'Day': days,
        'Temperature': temperatures
    }
)
df

Day  Temperature
0     Monday           72
1    Tuesday           68
2  Wednesday           74
3   Thursday           71
4     Friday           69
5   Saturday           73
6     Sunday           75

In [ ]:
max_temperature = df['Temperature'].max()
print(f"Maximum temperature: {max_temperature}")
print(f"Day with maximum temperature: {df['Day'][df['Temperature'] == max_temperature].values[0]}")

Maximum temperature: 75
Day with maximum temperature: Sunday


## 3. Stock Price Simulation

In [ ]:
df = pd.DataFrame(
    data = {
        'Day': np.arange(1, 6),                               # Days from 1 to 5
        'Price': np.random.normal(loc=100, scale=10, size=5)  # Random stock prices around 100
    }
)
df

Day       Price
0    1   91.918387
1    2   96.698412
2    3   89.202757
3    4  114.689791
4    5  100.187555

In [ ]:
# calculate percentage change in price day-to-day
df['Percentage_Change'] = df['Price'].pct_change() * 100
df

Day       Price  Percentage_Change
0    1   91.918387                NaN
1    2   96.698412           5.200293
2    3   89.202757          -7.751580
3    4  114.689791          28.572024
4    5  100.187555         -12.644748



---



# Bonus Question:
## Multi-Dimensional Data Analysis

In [ ]:
sales = np.random.choice(
    np.arange(80, 101, 5), # Only avaiable choices: 80, 85, 90, 95, 100
    size=(3, 4, 7)         # Dimensions of 3D array
)
sales

array([[[ 95,  90, 100,  85,  95,  80,  85],
        [ 95, 100,  90,  95,  90, 100, 100],
        [ 85,  95,  90,  80,  85,  80,  85],
        [ 80,  95,  80,  85,  80,  85, 100]],

       [[100,  90,  95,  80,  95, 100,  90],
        [ 95,  80,  80,  85,  95,  95, 100],
        [ 95,  80,  85,  95,  95,  85,  90],
        [ 80, 100,  95,  85,  80,  90,  85]],

       [[ 95,  85,  95,  90,  80,  80,  90],
        [ 80,  85, 100,  95, 100,  95,  90],
        [ 90,  80,  90,  85,  80,  95,  95],
        [ 95,  85,  80,  80,  80,  85, 100]]])

In [ ]:
total_sales = sales.sum(axis=(1, 2))
total_sales

array([2505, 2520, 2480])

In [139]:
for product in range(sales.shape[0]):
    sales_per_day = sales[product].sum(axis=0)
    highest_day_sale = sales_per_day.max()
    highest_day = np.where(sales_per_day == highest_day_sale)[0][0]
    print(f"Product {product + 1} had the highest sales on day {highest_day + 1} with a sale of {highest_day_sale}")

Product 1 had the highest sales on day 2 with a sale of 380
Product 2 had the highest sales on day 1 with a sale of 370
Product 3 had the highest sales on day 7 with a sale of 375
